# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UpstashRedisLocal < Formula
  desc "upstash-redis-local - Test @upstash/redis locally!"
  homepage ""
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DarthBenro008/upstash-redis-local/releases/download/1.0/upstash-redis-local_1.0_Darwin_arm64.tar.gz"
      sha256 "f0b888dff05268f6ddc5e0faa3186c0e434667885718a7fb7cec1dba142f41be"

      def install
        bin.install "upstash-redis-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DarthBenro008/upstash-redis-local/releases/download/1.0/upstash-redis-local_1.0_Darwin_x86_64.tar.gz"
      sha256 "ca1c2d073bbeb9c7ec90b920519af8eb7e6155eb083b4815158a10d25648a475"

      def install
        bin.install "upstash-redis-local"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DarthBenro008/upstash-redis-local/releases/download/1.0/upstash-redis-local_1.0_Linux_arm64.tar.gz"
      sha256 "0bef847d4924d17246d3aa9cd86011bc5229ba74a01e91ccc224a02502fc6ff1"

      def install
        bin.install "upstash-redis-local"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DarthBenro008/upstash-redis-local/releases/download/1.0/upstash-redis-local_1.0_Linux_x86_64.tar.gz"
      sha256 "0063812fa26e70fb420b8d41235b4e996fa4de53244928c48f7dbfa465173ce8"

      def install
        bin.install "upstash-redis-local"
      end
    end
  end
end
